Repository pickleheads/cookbook, pull requests merged in 2020-04, with the labels that each got.

#7 Create basic python serverless function that accepts a url string and…
  server/.gitignore
  server/api/webscrape.py
Labels: Status: Ready for Review, Type: Enhancement

#6 fix: Checkboxes in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Type: Bug

#10 feat: Ah so clean
  .github/workflows/pr.yml
Labels: Priority: Critical

#14 feat: use Flask instead of default http library
  packages/server/api/webscrape.py
  packages/server/requirements.txt
Labels: Type: Enhancement

#15 fix: Make web develop script work on Windows
  packages/web/package-lock.json
  packages/web/package.json
Labels: Type: Bug
